/*	Recinto  
	Espectaculos
	Representacion
	Entrada
	Espectador 
	Precio_Representacion
	Asiento*/
	CREATE TABLE espectador(
	dniESPECTADOR NVARCHAR (50) NOT NULL,
	nomESPECTADOR NVARCHAR (50) NOT NULL,
	dirESPECTADOR NVARCHAR (50) NOT NULL,
	telESPECTADOR NVARCHAR (50) NOT NULL,
	ciuESPECTADOR NVARCHAR (50) NOT NULL,
	numerotarjerta NVARCHAR (50) NOT NULL,
	CONSTRAINT pk_espectador_dniespectador PRIMARY KEY (dniESPECTADOR),
	);
	CREATE TABLE recinto(
	codRECINTO NVARCHAR (50) NOT NULL,
	nomRECINTO NVARCHAR (50) NOT NULL,
	dirRECINTO NVARCHAR (50) NOT NULL,
	ciuRECINTO NVARCHAR (50) NOT NULL,
	telRECINTO NVARCHAR (50) NOT NULL,
	horRECINTO TIME NOT NULL,
	CONSTRAINT pk_recinto_codRecinto PRIMARY KEY (codRECINTO),

	);
	CREATE TABLE espectaculo (
	codESPECTACULO NVARCHAR (50) NOT NULL,
	nomESPECTACULO NVARCHAR (50) NOT NULL,
	tipoESPECTACULO NVARCHAR (50) ,
	fechainicioESPECTACULO NVARCHAR (50) NOT NULL,
	fechafinalESPECTACULO DATE NOT NULL,
	interpreteESPECTACULO NVARCHAR NOT NULL,
	codRECINTO NVARCHAR (50) NOT NULL,
	CONSTRAINT pk_espectaculo_codESPECTACULO PRIMARY KEY (codESPECTACULO),
	CONSTRAINT fk_espectaculos_codRECINTO FOREIGN KEY codRECINTO REFERENCES recinto(codRECINTO),
	);
	CREATE TABLE representacion (
	codREPRESENTACION NVARCHAR (50) NOT NULL,
	codESPECTACULO NVARCHAR (50) NOT NULL,
	fechaREPRESENTACION DATE NOT NULL,
	horaREPRESENTACION TIME NOT NULL,
	CONSTRAINT pk_representacion_CodRepresentacion PRIMARY KEY (codREPRESENTACION),
	CONSTRAINT fk_representacion_CodESPECTACULO FOREIGN KEY (codESPECTACULO) REFERENCES espectaculo(codESPECTACULO),
	);
	CREATE TABLE asiento(
	numASIENTO NVARCHAR (50) NOT NULL,
	filASIENTO INT NOT NULL,
	codRECINTO NVARCHAR (50) NOT NULL,
	CONSTRAINT PK_asiento_ PRIMARY KEY (numASIENTO,filASIENTO),
	CONSTRAINT uniq_fila UNIQUE (filASIENTO),
	);
	CREATE TABLE entrada (
	codENTRADA NVARCHAR (50) NOT NULL,
	codREPRESENTACION NVARCHAR (50) NOT NULL,
	codRECINTO NVARCHAR (50) NOT NULL,
	numASIENTO NVARCHAR (50) NOT NULL,
	filASIENTO INT NOT NULL,
	dniESPECTADOR NVARCHAR (50) NOT NULL,
	CONSTRAINT pk_entrada_CODentrada PRIMARY KEY (codENTRADA),
	CONSTRAINT fk_entrada_codRepesentacion FOREIGN KEY (codREPRESENTACION) REFERENCES representacion(codREPRESENTACION),
	CONSTRAINT fk_entrada_DNIespectador FOREIGN KEY (codRECINTO) REFERENCES recinto(codRECINTO),
	CONSTRAINT fk_entrada_numAsiento FOREIGN KEY (numASIENTO) REFERENCES asiento(numASIENTO),
	CONSTRAINT fk_entrada_filAsiento FOREIGN KEY (filASIENTO) REFERENCES asiento(filASIENTO),
	);
	CREATE TABLE precio_representacion(
	codESPECTACULO NVARCHAR (50) NOT NULL,
	codREPRESENTACION NVARCHAR (50) NOT NULL,
	pvpESPECTACULO NVARCHAR (50) NOT NULL,
	CONSTRAINT pk_precio_representacion PRIMARY KEY (codESPECTACULO,codREPRESENTACION),
	CONSTRAINT fk_precio_codESPECTACULOS FOREIGN KEY (codESPECTACULO) REFERENCES espectaculo(codESPECTACULO),
	CONSTRAINT fk_precio_codRepresentacion FOREIGN KEY (codREPRESENTACION) REFERENCES representacion (codREPRESENTACION),
	CONSTRAINT fk_precio_pvpESPECTACULO FOREIGN KEY (pvpESPECTACULO) REFERENCES espectaculo(pvpESPECTACULO), 
	);